### ISSUE TITLE
Bad line from statsd server 

### ISSUE THREAD

**Issue by mydiemho** [airbnb/kafka-statsd-metrics2#7]
Hi,

I'm running etsy/statsd server on Ubuntu 14.04 with 

Java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
# 

My statsd server is spitting out debug msg about "Bad line".

Here are a few of the samples:

24 Jun 22:54:49 - DEBUG: kafka.server.ReplicaManager.IsrShrinksPerSec.1MinuteRate:0|g
24 Jun 22:54:59 - DEBUG: kafka.server.ReplicaManager.IsrExpandsPerSec.meanRate:0.00275|g
24 Jun 22:55:09 - DEBUG: Bad line: 5969158614627,g,#networkProcessor in msg "kafka.network.SocketServer.IdlePercent.count:5969158614627|g|#networkProcessor:2"

**Comment by alexism** [comment]
Hi @mydiemho ,

this is because by default metrics tags are reported. In your example it's the `#networkProcessor:2`.
Tags are an extension. See https://github.com/airbnb/kafka-statsd-metrics2#040

You can disable tags by adding `external.kafka.statsd.tag.enabled=false` in your `server.properties`.

Alexis

**Comment by mydiemho** [comment]
Thank you for the explanation.
